### ISSUE TITLE
`radio1` gets disabled when there's two enabled SSID on it

### ISSUE THREAD

**Issue by NatoBoram** [kaloz/mwlwifi#406]
I have 2 SSID configured on my `radio1`, but I can only get one to work.

Only first enabled:
![first enabled](https://user-images.githubusercontent.com/10495562/162020906-50f4da6b-c2ab-4a9f-badd-f5950e891c67.png)
Both enabled:
![both enabled](https://user-images.githubusercontent.com/10495562/162021054-767592c5-f4d7-4be4-90e7-8d6938d498d9.png)
Only second enabled:
![second enabled](https://user-images.githubusercontent.com/10495562/162021359-ff61ed98-5e41-483e-8e6a-b57385710285.png)

```yaml
OS: OpenWrt SNAPSHOT armv7l 
Host: Linksys WRT3200ACM 
Kernel: 5.10.109 
Uptime: 34 mins 
Packages: 208 (opkg) 
Shell: ash 
Terminal: /dev/pts/0 
CPU: Marvell Armada 380/385 (Device Tree) (2) 
Memory: 226MiB / 496MiB 
```

This is my configuration for the Wi-Fi

```bash
uci set wireless.default_radio0.key='***********'
uci set wireless.default_radio0.ssid='Nato'
uci set wireless.default_radio0.encryption='psk2'

uci set wireless.default_radio1.key='***********'
uci set wireless.default_radio1.ssid='Nato'
uci set wireless.default_radio1.encryption='psk2'

uci set wireless.default_radio2.key='***********'
uci set wireless.default_radio2.ssid='Nato'
uci set wireless.default_radio2.encryption='psk2'

uci set wireless.wifinet3=wifi-iface
uci set wireless.wifinet3.ssid='Free Wi-Fi'
uci set wireless.wifinet3.encryption='none'
uci set wireless.wifinet3.device='radio1'
uci set wireless.wifinet3.mode='ap'
uci set wireless.wifinet3.network='lan'
uci set wireless.wifinet3.isolate='1'

uci set wireless.radio0.channel='auto'
uci set wireless.radio1.channel='auto'
uci set wireless.radio2.channel='auto'
```

Please let me know if you need more information and how I can get it!
